<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function recipes_magazin_theme_registry_alter(&$theme_registry) {
  $theme_registry['views_view_grid']['path'] = \Drupal::service('extension.list.module')->getPath('recipes_magazin') . '/templates';
}

/**
 * Implements hook_page_attachments_alter().
 */
function recipes_magazin_page_attachments_alter(array &$attachments) {
  // Only support materialize for the home page and the tutorials.
  $path = \Drupal::request()->getPathInfo();
  if (in_array($path, ['/', '/help/tutorials'])) {
    $attachments['#attached']['library'][] = 'recipes_magazin/recipes_magazin.materialize';
  }
}
