<?php

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_type_build().
 */
function contenta_enhancements_entity_type_build(array &$entity_types) {
  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  
  $entity_types['entity_view_display']->set('admin_permission', 'administer display modes');
  $entity_types['entity_form_display']->set('admin_permission', 'administer display modes');
}


/**
 * Implements hook_entity_base_field_info_alter().
 */
function contenta_enhancements_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields['title']->setDisplayConfigurable('view', TRUE);
  }
}
