<?php

/**
 * @file
 * Module installation file.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function recipes_magazin_contenta_install() {
  \Drupal::service('recipes.migration_runner')->run([
    'recipes_magazin_contenta__images',
    'recipes_magazin_contenta__media_images',
    'recipes_magazin_contenta__authors',
    'recipes_magazin_contenta__pages',
    'recipes_magazin_contenta__embeddable',
    'recipes_magazin_contenta__tutorial',
    'recipes_magazin_contenta__consumers',
  ]);

  // Grant the "access user profiles" permission to all users by default.
  if (\Drupal::moduleHandler()->moduleExists('user')) {
      user_role_grant_permissions(RoleInterface::ANONYMOUS_ID, [
          'access user profiles',
      ]);
      user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, [
          'access user profiles',
      ]);
  }
}

/**
 * Implements hook_uninstall().
 */
function recipes_magazin_contenta_uninstall() {
  \Drupal::service('recipes.migration_runner')->remove([
    'recipes_magazin_contenta__images',
    'recipes_magazin_contenta__media_images',
    'recipes_magazin_contenta__authors',
    'recipes_magazin_contenta__pages',
    'recipes_magazin_contenta__embeddable',
    'recipes_magazin_contenta__tutorial',
    'recipes_magazin_contenta__consumers',
  ]);
}
