<?php

/**
 * @file
 * Module installation file.
 */

/**
 * Implements hook_install().
 */
function recipes_magazin_contenta_install() {
  \Drupal::service('recipes.migration_runner')->run([
    'recipes_magazin_contenta__images',
    'recipes_magazin_contenta__media_images',
    'recipes_magazin_contenta__authors',
    'recipes_magazin_contenta__pages',
    'recipes_magazin_contenta__embeddable',
    'recipes_magazin_contenta__tutorial',
    'recipes_magazin_contenta__consumers',
  ]);
}

/**
 * Implements hook_uninstall().
 */
function recipes_magazin_contenta_uninstall() {
  \Drupal::service('recipes.migration_runner')->remove([
    'recipes_magazin_contenta__images',
    'recipes_magazin_contenta__media_images',
    'recipes_magazin_contenta__authors',
    'recipes_magazin_contenta__pages',
    'recipes_magazin_contenta__embeddable',
    'recipes_magazin_contenta__tutorial',
    'recipes_magazin_contenta__consumers',
  ]);
}
