<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_bundle_create().
 */
function contenta_graphql_entity_bundle_create($entity_type_id, $bundle) {
  // By default, expose created content type as GraphQL Schema
  $config = \Drupal::service('config.factory')->getEditable('graphql_content.schema');
  $bundles = $config->get('types.node.bundles');
  $bundles[$bundle] = ['exposed' => true, 'view_mode' => 'node.full'];
  $config->set('types.node.bundles', $bundles)->save();

  //@todo: add mutations support.
}

/**
 * Implements hook_entity_bundle_delete().
 */
function contenta_graphql_entity_bundle_delete($entity_type_id, $bundle) {
  // By default, expose created content type as GraphQL Schema
  $config = \Drupal::service('config.factory')->getEditable('graphql_content.schema');
  $bundles = $config->get('types.node.bundles');
  unset($bundles[$bundle]);
  $config->set('types.node.bundles', $bundles)->save();

  //@todo: add mutations support.
}
