<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function contenta_graphql_form_node_type_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'contenta_graphql_node_type_submit';
    }
  }
}

function contenta_graphql_node_type_submit(&$form, FormStateInterface $form_state) {
  // By default expose created content type as GraphQL Schema
  $config = \Drupal::service('config.factory')->getEditable('graphql_content.schema');
  $bundles = $config->get('types.node.bundles');
  $bundles[$form_state->getValue('type')] = ['exposed' => true, 'view_mode' => 'node.full'];
  $config->set('types.node.bundles', $bundles)->save();

  //@todo expose mutations
}

